<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome">
								<?= $this->view->nome_usuario['nome'] ?>
							</span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor">
								<?= $this->view->total_tweets['total_tweets'] ?>
							</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor">
								<?= ($this->view->total_seguindo['total_seguindo'])?>
							</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor">
								<?= ($this->view->total_seguidores['total_seguidores']) ?>
							</span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="post" action="/tweet">
						<textarea name="tweet" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>


			<?php foreach ($this->view->tweets as $tweets => $value) { ?>
				
				<div class="row tweet">
					<div class="col">
						<p><strong><?= ucfirst($value['nome'])?></strong> <small><span class="text text-muted">- <?= $value['data'] ?></span></small></p>
						<p><?= $value['tweet'] ?></p>

						<br />

						<?php if($value['id_usuario'] == $_SESSION['id']) { ?>
		
							<form action="" method="GET">

								<!-- Não é utilizado -->
								<input type="hidden" name="id_tweet" value="<?=$value['id']?>">

								<div class="col d-flex justify-content-end">
									<!--<button id="btnExcluir" type="submit" class="btn btn-danger"><small>Remover</small></button>-->
									<a href="/deletar?id_tweet=<?=$value['id']?>" data-confirm="" id="btnExcluir" class="btn btn-danger"><small>Remover</small></a>
								</div>
							</form>		
						<?php } ?>

					</div>
				</div>
			<?php } ?>

			



		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>